INSERT INTO "Hamburguer" ("name", "description", "price", "ingredients", "size", "categoryId") VALUES 
('Hambúrguer Picante', 'Carne bovina apimentada com jalapeños e queijo cheddar.', 20.99, ARRAY['pão', 'carne bovina apimentada', 'jalapeños', 'queijo cheddar', 'molho picante'], 'Médio', 1),
('Cheeseburger de Cordeiro', 'Hambúrguer gourmet de carne de cordeiro com queijo feta.', 27.99, ARRAY['pão', 'carne de cordeiro', 'queijo feta', 'rúcula', 'molho de iogurte'], 'Grande', 1),
('X-Salada', 'Hambúrguer com queijo, alface, tomate e molho especial.', 19.49, ARRAY['pão', 'carne bovina', 'queijo cheddar', 'alface', 'tomate', 'molho especial'], 'Médio', 1),
('Cheeseburger Gourmet', 'Hambúrguer premium com queijo suíço e cogumelos.', 28.99, ARRAY['pão', 'carne bovina premium', 'queijo suíço', 'cogumelos', 'molho trufado'], 'Grande', 1),
('Hambúrguer de Salmão', 'Hambúrguer de salmão grelhado com rúcula e maionese de ervas.', 23.99, ARRAY['pão', 'salmão grelhado', 'rúcula', 'maionese de ervas'], 'Médio', 1),
('X-Egg', 'Hambúrguer com queijo, ovo frito e bacon.', 21.99, ARRAY['pão', 'carne bovina', 'queijo cheddar', 'ovo frito', 'bacon', 'molho especial'], 'Médio', 1),
('Cheeseburger Light', 'Hambúrguer com carne magra, queijo light e vegetais frescos.', 19.49, ARRAY['pão integral', 'carne bovina magra', 'queijo light', 'alface', 'tomate', 'pepino'], 'Médio', 1),
('Hambúrguer Barbecue', 'Hambúrguer com molho barbecue e cebola caramelizada.', 22.49, ARRAY['pão', 'carne bovina', 'queijo cheddar', 'cebola caramelizada', 'molho barbecue'], 'Grande', 1),
('X-Frango', 'Hambúrguer com frango grelhado, alface e maionese.', 17.99, ARRAY['pão', 'frango grelhado', 'alface', 'maionese'], 'Médio', 1),
('Cheeseburger Italiano', 'Hambúrguer com carne bovina, queijo provolone e rúcula.', 24.99, ARRAY['pão', 'carne bovina', 'queijo provolone', 'rúcula', 'molho pesto'], 'Grande', 1),
('Hambúrguer Texano', 'Hambúrguer com queijo cheddar, cebola frita e molho picante.', 25.99, ARRAY['pão', 'carne bovina', 'queijo cheddar', 'cebola frita', 'molho picante'], 'Grande', 1),
('Cheeseburger Bacon e Queijo', 'Hambúrguer com bacon crocante e muito queijo.', 23.99, ARRAY['pão', 'carne bovina', 'bacon', 'queijo cheddar', 'molho especial'], 'Médio', 1),
('Hambúrguer com Guacamole', 'Hambúrguer com guacamole e queijo cheddar.', 26.99, ARRAY['pão', 'carne bovina', 'queijo cheddar', 'guacamole', 'tomate'], 'Grande', 1),
('X-Costela', 'Hambúrguer com carne de costela desfiada e molho barbecue.', 28.49, ARRAY['pão', 'costela desfiada', 'queijo cheddar', 'molho barbecue'], 'Grande', 1),
('Hambúrguer de Peixe', 'Hambúrguer com peixe empanado, alface e maionese.', 19.99, ARRAY['pão', 'peixe empanado', 'alface', 'maionese'], 'Médio', 1);