INSERT INTO "Savory" ("name", "description", "price", "ingredients", "categoryId") VALUES
('Coxinha de Frango', 'Frango desfiado temperado e empanado.', 5.50, ARRAY['frango', 'catupiry', 'massa de farinha de trigo', 'farinha de rosca'], 3),
('Esfiha de Carne', 'Esfiha aberta com recheio de carne moída e temperos.', 4.50, ARRAY['carne moída', 'cebola', 'massa de esfiha', 'pimenta-do-reino', 'sal'], 3),
('Quibe Recheado', 'Quibe de carne moída recheado com catupiry.', 6.00, ARRAY['carne moída', 'trigo para quibe', 'catupiry', 'cebola', 'hortelã'], 3),
('Bolinho de Bacalhau', 'Bolinho de bacalhau temperado e empanado.', 6.50, ARRAY['bacalhau', 'batata', 'salsinha', 'cebola', 'farinha de trigo'], 3),
('Empada de Palmito', 'Empada recheada com palmito cremoso.', 4.50, ARRAY['massa de empada', 'palmito', 'requeijão', 'cebola', 'azeitona'], 3),
('Pastel de Queijo', 'Pastel frito com recheio de queijo.', 4.00, ARRAY['massa de pastel', 'queijo mussarela', 'orégano'], 3),
('Coxinha de Calabresa', 'Coxinha recheada com calabresa e queijo.', 5.50, ARRAY['massa de farinha de trigo', 'calabresa', 'queijo'], 3),
('Bolinha de Queijo', 'Bolinha de queijo empanada e frita.', 3.50, ARRAY['queijo mussarela', 'farinha de trigo', 'farinha de rosca', 'ovo'], 3),
('Enroladinho de Salsicha', 'Enroladinho de massa com salsicha.', 3.00, ARRAY['massa de pão', 'salsicha', 'ketchup', 'mostarda'], 3),
('Risole de Camarão', 'Risole recheado com camarão e queijo.', 7.00, ARRAY['massa de risole', 'camarão', 'queijo', 'salsinha'], 3),
('Pastel de Carne', 'Pastel recheado com carne moída e temperos.', 4.50, ARRAY['massa de pastel', 'carne moída', 'cebola', 'pimenta-do-reino'], 3),
('Bolinho de Aipim com Carne Seca', 'Bolinho de aipim recheado com carne seca.', 6.50, ARRAY['aipim', 'carne seca', 'farinha de trigo', 'salsinha'], 3),
('Croquete de Carne', 'Croquete de carne moída temperado.', 4.00, ARRAY['carne moída', 'farinha de rosca', 'ovo', 'cebola'], 3),
('Empada de Camarão', 'Empada recheada com camarão e requeijão.', 5.00, ARRAY['massa de empada', 'camarão', 'requeijão', 'cebolinha'], 3),
('Esfiha de Queijo', 'Esfiha aberta com recheio de queijo temperado.', 4.50, ARRAY['massa de esfiha', 'queijo mussarela', 'orégano'], 3);
